### PR TITLE
#14 - token search: enhance algorithm for es6 and split out jump logic due to its growing complexity

### LINKED ISSUE #14: enhance test suite for ES6 code
### Description of the issue

some ES6 features may not work with this plugin properly, so test cases are required

### Steps to reproduce

One example would be curly brackets in declarations

``` javascript
const { foo, bar } = obj;
```

### Expected behavior

test cases to ensure proper behavior

### PR DESCRIPTION
**Pull request by Ma27**
### Overview

some es6 style code like ``const { foo, bar } = blah`` didn't work properly with this plugin.
This PR aims to support this properly.
Due to the growing complexity of the token jump logic, the searcher for the punctuator has been splitted up into its own module.

### Related/Resolved tickets

resolves #14

### CODE REVIEW

File: lib/util/findNextPunctuators.js [hunk 1]
```diff
@@ -43,51 +44,31 @@ module.exports = function(node, source, lines) {
...
-      }
-      return after;
-    }
 
-    var result = [], punctuators = getPunctuators(node, source), next = findNextExpressionToken(source, node);
+    var next = findNextExpressionToken(source, node);
     if (typeof next === 'undefined') {
       if (isVariableAssignment(node) && node.declarations.length > 1) {
-        return punctuators;
+        return [];
```
Comment (Ma27) [inline lib/util/findNextPunctuators.js]: this is nnot needed anymore. THe ``punctuators`` will be computed in ``getDeclarations`` and everything will end up in the ``finally`` clause, so this condition should be removed, but the error should be thrown at every time when ``next`` is ``undefined``
