### PR TITLE
#13 - token search: check for deeper assignment structures in second assignment

### LINKED ISSUE #13: fix behavior with multiple declarations and ternary operators
### Description of the issue

when declaring multiple variables and using ternaries inside, it will cause issues.

### Steps to reproduce

``` javascript
{
  code: [
    'obj.expr = [];',
    'var foo, bar = baz = true ? {} : [];'
  ].join('\n'),
  errors: [{
    message: 'Invalid indent!'
  }]
}
```

### PR DESCRIPTION
**Pull request by Ma27**
### Overview

when multiple vars are declared in the next line, the searcher doesn't work properly.
One example to show what's happening:

``` javascript
var foo = [];
var blah, foobar = {};
```

In this case the punctuator isn't detected properly which caused missing CS reports

### Related/Resolved tickets

resolves #13

### CODE REVIEW

File: lib/util/findNextPunctuators.js [hunk 1]
```diff
@@ -44,87 +43,52 @@ module.exports = function(node, source, lines) {
...
-      // checks whether a new variable is introduced
-      // or an existing one will be changed.
-      var punctuator = isNewVariable(after) ? source.getTokenAfter(after, 1) : source.getTokenAfter(after);
-
-      if (isPunctuatorAssignment(punctuator)) {
-        punctuators.push(punctuator);
+    function findProperPunctuator(next, x) {
+      var after = source.getTokenAfter(next, 2 - x);
+      if (after.value !== '=') {
+        return findProperPunctuator(after, 1);
```
Comment (Ma27) [inline lib/util/findNextPunctuators.js]: the recursion may cause issues if the second line doesn't have any vars declared
